export const WORD_MIN_LENGTH = 4;
export const PANGRAM_SCORE = 10;
export const GAUGE_WIDTH = 250;

export const GAME = {
  LOADING: "INVALID_LETTERS",
  READY: "READY",
  ERROR: "ERROR"
};

export const WORD = {
  INVALID_LETTERS: "INVALID_LETTERS",
  WORD_TOO_SHORT: "WORD_TOO_SHORT",
  NOT_FOUND: "NOT_FOUND",
  MANDATORY_LETTER_MISSING: "MANDATORY_LETTER_MISSING",
  ALREADY_PLAYED: "ALREADY_PLAYED",
  CORRECT: "CORRECT",
  PANGRAM: "PANGRAM"
};
