export const GAME = {
  LOADING: "INVALID_LETTERS",
  READY: "READY",
  ERROR: "ERROR",
};

export const WORD = {
  INVALID_LETTERS: "INVALID_LETTERS",
  NOT_FOUND: "NOT_FOUND",
  MANDATORY_LETTER_MISSING: "MANDATORY_LETTER_MISSING",
  ALREADY_PLAYED: "ALREADY_PLAYED",
  CORRECT: "CORRECT",
  PANGRAM: "PANGRAM",
};
